#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c mcr<tab>/do<tab>
#
# ...to quickly jump into mcrumm/dotfiles, for example.

cd "$PROJECTS/$1"
