cask_args appdir: '/Applications'

brew 'atuin'
brew 'autoconf'
brew 'coreutils'
brew 'curl'
brew 'delta'
brew 'fop'
brew 'gh'
brew 'git'
brew 'grc'
brew 'libxslt'
brew 'mise'
brew 'openssl'
brew 'wget'
brew 'wxwidgets'

cask 'font-jetbrains-mono'
cask 'font-monaspace'
cask 'font-source-code-pro'

cask '1password'
cask 'claude-code'
cask 'conductor'
cask 'ghostty'
cask 'handbrake-app'
cask 'iina'
cask 'livebook'
cask 'quicklook-video'
cask 'visual-studio-code'
cask 'vlc'
cask 'zed'
